database:
  driver: postgres
  name: postgres
  host: postgres
  port: 5432
  user: blacktop
  password: your_secure_password_here

daemon:
  sigs-dir: /app/symbolicator/kernel
  bind: 0.0.0.0:3993
  
logging:
  level: info
  format: text
  
server:
  read_timeout: 600s
  write_timeout: 600s
  idle_timeout: 620s