database:
  driver: postgres
  name: symbols
  host: localhost
  port: 5432
  user: symboluser
  password: symbolpass

daemon:
  sigs-dir: ./signatures/kernel

symbolicate:
  color: true
  demangle: true
  
logging:
  level: info 