# IPSW Daemon Configuration
daemon:
  host: 0.0.0.0
  port: 3993
  database:
    driver: postgres
    host: symbol-db
    port: 5432
    name: symbols
    user: symboluser
    password: symbolpass
  sigs-dir: /app/symbolicator/kernel

# Logging configuration  
logging:
  level: info
  
# Symbolication settings
symbolicate:
  color: true
  demangle: true 